# Generated by Django 4.0.4 on 2022-04-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=120, verbose_name='Language')),
                ('Code', models.CharField(max_length=10, verbose_name='Code')),
            ],
        ),
    ]
