# Generated by Django 4.0.4 on 2022-04-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_alter_languagemodel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagemodel',
            name='Code',
            field=models.CharField(max_length=255, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='languagemodel',
            name='Language',
            field=models.CharField(max_length=255, verbose_name='Language'),
        ),
    ]
