# Generated by Django 4.0.4 on 2022-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0005_alter_languagemodel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagemodel',
            name='Code',
            field=models.CharField(max_length=15, verbose_name='Code'),
        ),
    ]
